/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sad_viva;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.sound.sampled.LineEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.apache.poi.hssf.record.PageBreakRecord;

/**
 *
 * @author Inspiron 15
 */
public class database_loading extends javax.swing.JFrame {

    /**
     * Creates new form database_loading
     */
    public database_loading() {
        initComponents();
        databse_check();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 51));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 270, 30));

        jLabel7.setBackground(new java.awt.Color(255, 51, 0));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 270, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 270, 30));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 270, 40));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, 30));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RZK Technology Software Inc.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 520, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/7647bb7539382dd708010625c4598021.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 522));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("GREEN");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");

        } catch (Exception e) {
            e.printStackTrace();

        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new database_loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void databse_check() {

        new Thread(new Runnable() {
            @Override
            public void run() {

                for (int i = 0; i <= 100; i++) {
                    jLabel1.setVisible(true);
                        
                }
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    //Connection con=DriverManager.getconnection(url,"root","123"); 
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/information_schema", "root", "123");
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery("select SCHEMA_NAME from SCHEMATA where SCHEMA_NAME='sad_viva'");
                    if (rs.next()) {
                        
                try {

                    Thread.sleep(2000);

                    jLabel4.setText("Checking DataBase...");
                    Thread.sleep(3000);

                    jLabel5.setText("Loading Backgrounds..");
                    Thread.sleep(3000);

                    jLabel6.setText("Loading Software..");

                    Thread.sleep(3000);
                    jLabel7.setText("Loading Success..");
                    Thread.sleep(3000);
                    jLabel2.setText("Start");
                    Thread.sleep(1000);

                } catch (Exception e) {

                }
                dispose();
                new login().setVisible(true);
                       

                    } else {
                        jLabel4.setText("Checking DataBase...");
                        Thread.sleep(3000);
                        jLabel5.setText("Loading failed !");
                        Thread.sleep(1000);
                        dispose();
                        JOptionPane.showMessageDialog(null, "Your Database is Lost Please Restore and try Again", "Database warning", HEIGHT);
                        new Restore().setVisible(true);
                        

                    }
                   

                } catch (Exception e) {

                }

               


            }

        }).start();

    }
}
