/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sad_viva;

import java.sql.ResultSet;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Inspiron 15
 */
public class forget_Password extends javax.swing.JFrame {

    /**
     * Creates new form forget_Password
     */
    public forget_Password() {
        initComponents();
        
        
       
        try {

            ResultSet rs = Jdbc.getData("select email from login");
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("email"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login_1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 30, 50));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jButton1.setText("     Get Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 140, 50));

        jComboBox1.setBackground(new java.awt.Color(102, 255, 102));
        jComboBox1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 0, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Email" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/Untitled.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jComboBox1.getSelectedIndex()==0){
            
            JOptionPane.showMessageDialog(null, "Please Select Validate Email Address");
            
        }else{

        try {
            ResultSet rs = Jdbc.getData("select * from login where email = '" + jComboBox1.getSelectedItem().toString() + "'");
            while (rs.next()) {
                Email.e_mail_it(rs.getString("email"), rs.getString("user_name") + "Your Password", "     Password -" + rs.getString("password"), "");
                JOptionPane.showMessageDialog(null, rs.getString("user_name")  +  " - Password is Send to your Email Check Your Email Account");
            }
            
        }catch(javax.mail.internet.AddressException e){
            
                 JOptionPane.showMessageDialog(null, "Check Your Email Address And Try again");

        } catch (java.net.UnknownHostException e1) {
            JOptionPane.showMessageDialog(null, "Check Your Email Connection");
        } catch (com.sun.mail.util.MailConnectException e2) {

            JOptionPane.showMessageDialog(null, "First Check Your Internet Connection");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "First Check Your Internet Connection");
        }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                try {
            com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("GREEN");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");

        } catch (Exception e) {
            e.printStackTrace();

        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
